In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [3]:
X_train[:5]

array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2]])

In [4]:
y_train[:5]

array([0, 0, 1, 0, 0])

In [60]:
def KNN(X_train, X_test, y_train, y_test, k = 3):
    y_pred = []
    for _,x in enumerate(X_test):
        distances = []
        labels = []
        for i, x_train in enumerate(X_train):
            distance = euclidean_distance(x, x_train)
            distances.append((distance, i))
        distances = sorted(distances)[:k]
        for d, ii in distances:
            labels.append(y_train[ii])
        most_common_label = common(labels)
        y_pred.append(most_common_label)
        
    return y_pred


In [57]:
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

In [58]:
def common(labels):
    most_common = 0
    mx = 0
    for label in labels:
        count = 0
        for label_ in  labels:
            if label == label:
                count += 1
        if mx < count:
            most_common = label
    return most_common
    

In [65]:
y_pred = KNN(X_train, X_test, y_train, y_test)
y_pred

[1,
 0,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0]

In [66]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
from matplotlib

In [69]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9333333333333333

In [72]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[10,  0,  0],
       [ 0,  8,  1],
       [ 0,  1, 10]], dtype=int64)